### ISSUE TITLE
tutorial 14 cut off

### ISSUE THREAD

**Issue by lschierer** [sdondley/Dist-Zilla-for-Beginners#1]
This was very useful, much better than the official tutorials at <https://dzil.org/tutorial/contents.html>, however, it appears that #14 is cut off, ending in the word "verss" in mid-sentence.  

Thanks for your help documenting the complex for the beginners out there!

**Comment by sdondley** [comment]
Glad you like the tutorial. I forgot I even wrote it. It looks like it was not finished. Unfortunately, I will not be finishing it.
